### PR TITLE
update option lang button on header

### PR DESCRIPTION
**Pull request by khengyun**
https://github.com/khengyun/FFood-shop/assets/78076796/9df948d5-f4d0-46dc-b63d-c524adda1033

### CODE REVIEW

**Comment by khengyun** [comment]
👋 @khengyun
Thank you for raising your pull request.
Please make sure you have followed our contributing guidelines. We will review it as soon as possible

**Comment by quzanh1130** [comment]
image

why not have language names?

**Comment by quzanh1130** [comment]
image
call icon on the left of phone number

please fix it and commit again

**Comment by khengyun** [comment]
> image call icon on the left of phone number
> 
> please fix it and commit again - sr i am gay

### ok. I will remove the phone number information from the header. because there is already such information in the footer. It's unprofessional if it's repeated continuously
image

**Comment by khengyun** [comment]
> image
> 
> why not have language names?

### fixed . ok ??
image

**Review by quzanh1130 — APPROVED** [review]
It is great!

**Pull request merged**
