### PR TITLE
[Update] update login with google feature 

### PR DESCRIPTION
**Pull request by khengyun**

### CODE REVIEW

**Comment by khengyun** [comment]
👋 @khengyun
Thank you for raising your pull request.
Please make sure you have followed our contributing guidelines. We will review it as soon as possible

**Comment by quzanh1130** [comment]
image

go to this step, I have this error

**Comment by khengyun** [comment]
@quzanh1130 have any video for this error ?.

**Comment by khengyun** [comment]
@tien-thanh-hua  Checking this function for me, almost only @quzanh1130  has an error that cannot log in with this function. @HuynhVuGenius vs @khengyun  oke with this.

**Pull request merged**
